#!/bin/sh

## Don't catch 2 (SIGINT) and 17 (SIGCHLD) to allow the user 
## to quit the session using ctrl-C shortcut
trap "" 1 3 4 5 6 7 8 9 10 11 12 13 14 15 16 18 19 20 21 22 23 24 25 26 27 28 29 30 31

clear
echo "--------------------------------------------------------------------------------"
echo "You are now connected to the meep's serial proxy service."
echo "--------------------------------------------------------------------------------"
echo ""

blade_ip=`mysql -u ssh -psraL89qr43pz -e "use ssh_accounts; select blade_ip from t_user where login='$LOGNAME'" | head -2 | tail -1`
port=`mysql -u ssh -psraL89qr43pz -e "use ssh_accounts; select port from t_user where login='$LOGNAME'" | head -2 | tail -1`
socat stdio,raw,echo=0 tcp-connect:$blade_ip:$port

## $HOME was set to [blade_ip]:[port] from nss
#socat stdio tcp-connect:$HOME
